name: graalpy-install-package
on:
  push:
    paths:
      - 'graalpy-install-package/**'
      - '.github/workflows/graalpy-install-package.yml'
  pull_request:
    paths:
      - 'graalpy-install-package/**'
      - '.github/workflows/graalpy-install-package.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'graalpy-install-package'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Set up virtual X11
        run: |
          sudo apt-get install xvfb
          Xvfb :19 -screen 0 1024x768x16 &
          echo "DISPLAY=:19" >> "$GITHUB_ENV"
      - name: Run 'graalpy-install-package'
        run: |
          cd graalpy-install-package
          mvn --no-transfer-progress clean package
          mvn exec:exec &
          PID=$!
          sleep 60
          kill $PID
        # Does not run native executable, as it requires the agent to run first
