name: graalpy-eval-demo
on:
  push:
    paths:
      - 'graalpy-eval-demo/**'
      - '.github/workflows/graalpy-eval-demo.yml'
  # pull_request: (requires EE, which is unavailable in PRs)
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'graalpy-eval-demo'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Run 'graalpy-eval-demo'
        run: |
          cd graalpy-eval-demo
          mvn --no-transfer-progress clean package
          mvn exec:exec
          mvn --no-transfer-progress clean -Pnative -DskipTests package
          ./target/eval_graalpy
